export const data = [
	{
		title: 'Jalan ruko sunat',
		img: '/img/ruko_sunat_01.jpeg',
		para: 'Pengaspalan jalan ruko sunat lokasi Cipanas puncak',
		type: 'snacks',
		id: 1,
	},
	{
		title: 'Jonggol',
		img: '/img/taman_jonggol_02.jpeg',
		para: 'Pengaspalan Taman Jonggol',
		type: 'lunch',
		id: 2,
	},
	{
		title: 'Hambalang',
		img: '/img/hambalang_01.jpeg',
		para: 'Pengaspalan proyek WASKITA Hambalang',
		type: 'dinner',
		id: 3,
	},
	{
		title: 'Ciampea',
		img: '/img/ciampea_01.jpeg',
		para: 'Pengaspalan di daerah ciampea bogor',
		type: 'snacks',
		id: 4,
	},
	{
		title: 'Villa',
		img: '/img/villa_duta_bogor_01.jpeg',
		para: 'Pengaspalan villa duta bogor',
		type: 'breakfast',
		id: 5,
	},
	{
		title: 'Villa',
		img: '/img/villa_bogor_indah_01.jpeg',
		para: 'Pengaspalan villa bogor indah',
		type: 'lunch',
		id: 6,
	},
	{
		title: 'Depok',
		img: '/img/depok_01.jpeg',
		para: 'Pengaspalan di daerah Depok',
		type: 'dinner',
		id: 7,
	},
	{
		title: 'Villa Gadog puncak',
		img: '/img/gadog_puncak_01.jpeg',
		para: 'Pengaspalan proyek perumaha Villa Gadog puncak di daerah gadog puncak bogor',
		type: 'snacks',
		id: 8,
	},
	{
		title: 'Cijeruk',
		img: '/img/cijeruk_02.jpeg',
		para: 'Pengsapalan di carport minimalis perumahan Cijeruk',
		type: 'breakfast',
		id: 9,
	},
	{
		title: 'Hotel Pajajran Bogor',
		img: '/img/pajajran_bogor_01.jpeg',
		para: 'Pengaspalan Hotel di daerah pajajaran bogor',
		type: 'lunch',
		id: 10,
	},
	{
		title: 'Pabrik tangerang',
		img: '/img/pabrik_gudang_tangerang_01.jpeg',
		para: 'Pengaspalan jalan pabrik dan gudang di daerah tangerang',
		type: 'dinner',
		id: 11,
	},
	{
		title: 'Pabrik bekasi',
		img: '/img/pabrik_gudang_bekasi_01.jpeg',
		para: 'Pengaspalan jalan pabrik dan gudang di daerah bekasi',
		type: 'snacks',
		id: 12,
	},
	{
		title: 'Sentul',
		img: '/img/sentul_01.jpeg',
		para: 'Pengaspalan gudang area sentul',
		type: 'breakfast',
		id: 13,
	},
	{
		title: 'Jalan Cipaku Ciapus',
		img: '/img/cipaku_ciapus_01.jpeg',
		para: 'Pengaspalan jalan daerah Cipaku Ciapus Bogor',
		type: 'breakfast',
		id: 13,
	},
];